name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    - uses: actions/checkout@v4

    # Install necessary PHP extensions for Laravel (mbstring, bcmath, intl)
    - run: sudo apt-get install -y php8.0-mbstring php8.0-bcmath php8.0-intl php8.0-sqlite3

    # Clear Composer cache to avoid issues with corrupted cache
    - run: composer clear-cache

    # Update Composer to the latest version
    - run: composer self-update

    # Copy .env file if it doesn't exist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Install Dependencies (composer install)
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --prefer-dist --no-progress

    # Generate Laravel application key
    - name: Generate key
      run: php artisan key:generate

    # Set proper directory permissions for Laravel (storage and bootstrap/cache)
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Create the SQLite database for testing
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Execute Laravel tests
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
